In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
# .T for transpose function to transpose the the whole array ment column convert into row and row convert into column \
arr.T

array([[6, 2, 9],
       [2, 8, 1],
       [4, 5, 9],
       [3, 1, 9]])

In [4]:
# flatten:- it is used to convert array of one diemention
a=arr.flatten()

In [5]:
a

array([6, 2, 4, 3, 2, 8, 5, 1, 9, 1, 9, 9])

In [6]:
type(a)

numpy.ndarray

In [7]:
len(a)

12

In [8]:
# expand_dims:- it is used to expand the diemention of the array if we take axis = 1 then it expanded by the column and axis =0 then expanded by the row
np.expand_dims(arr ,axis=1)

array([[[6, 2, 4, 3]],

       [[2, 8, 5, 1]],

       [[9, 1, 9, 9]]])

In [9]:
np.expand_dims(arr ,axis=0)

array([[[6, 2, 4, 3],
        [2, 8, 5, 1],
        [9, 1, 9, 9]]])

In [12]:
## squeeze is conver two d array to one d array
data=np.array(([1],[2],[3]))
np.squeeze(data)

array([1, 2, 3])

In [14]:
# repet function is used to repeat the element 
np.repeat(data ,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
# roll function is used to rool the element 
np.roll(data ,3)

array([[1],
       [2],
       [3]])

In [21]:
arr4=np.array([1,2,3,4])

In [24]:
# digonal function is used to represent the element of a list diognaly
np.diag(arr4)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# binary operation 
array1=np.random.randint(1,9,(4,5))

In [26]:
array2=np.random.randint(1,9,(4,5))

In [27]:
array1+array2

array([[ 7, 10,  5,  9, 10],
       [ 9,  7,  7, 10, 11],
       [10, 11, 11,  3, 10],
       [ 9,  8, 13,  7,  4]])

In [28]:
array1-array2

array([[ 5, -2, -3,  3,  6],
       [ 1,  1, -1, -6, -3],
       [ 2,  5, -5,  1, -2],
       [ 7,  0,  1, -1,  0]])

In [29]:
array1*array2

array([[ 6, 24,  4, 18, 16],
       [20, 12, 12, 16, 28],
       [24, 24, 24,  2, 24],
       [ 8, 16, 42, 12,  4]])

In [30]:
array1/array2

array([[6.        , 0.66666667, 0.25      , 2.        , 4.        ],
       [1.25      , 1.33333333, 0.75      , 0.25      , 0.57142857],
       [1.5       , 2.66666667, 0.375     , 2.        , 0.66666667],
       [8.        , 1.        , 1.16666667, 0.75      , 1.        ]])

In [31]:
array1%array2

array([[0, 4, 1, 0, 0],
       [1, 1, 3, 2, 4],
       [2, 2, 3, 0, 4],
       [0, 0, 1, 3, 0]])

In [32]:
~array1

array([[-7, -5, -2, -7, -9],
       [-6, -5, -4, -3, -5],
       [-7, -9, -4, -3, -5],
       [-9, -5, -8, -4, -3]])

In [33]:
# operation in string arrays
array3=np.array(["shivank","pandey"])

In [34]:
array3

array(['shivank', 'pandey'], dtype='<U7')

In [35]:
np.char.capitalize(array3)

array(['Shivank', 'Pandey'], dtype='<U7')

In [36]:
np.char.title(array3)

array(['Shivank', 'Pandey'], dtype='<U7')

In [37]:
np.char.upper(array3)

array(['SHIVANK', 'PANDEY'], dtype='<U7')

In [38]:
np.char.lower(array3)

array(['shivank', 'pandey'], dtype='<U7')

In [40]:
# mathmatic function
array1

array([[6, 4, 1, 6, 8],
       [5, 4, 3, 2, 4],
       [6, 8, 3, 2, 4],
       [8, 4, 7, 3, 2]])

In [42]:

np.sin(array1)

array([[-0.2794155 , -0.7568025 ,  0.84147098, -0.2794155 ,  0.98935825],
       [-0.95892427, -0.7568025 ,  0.14112001,  0.90929743, -0.7568025 ],
       [-0.2794155 ,  0.98935825,  0.14112001,  0.90929743, -0.7568025 ],
       [ 0.98935825, -0.7568025 ,  0.6569866 ,  0.14112001,  0.90929743]])

In [43]:
np.cos(array1)

array([[ 0.96017029, -0.65364362,  0.54030231,  0.96017029, -0.14550003],
       [ 0.28366219, -0.65364362, -0.9899925 , -0.41614684, -0.65364362],
       [ 0.96017029, -0.14550003, -0.9899925 , -0.41614684, -0.65364362],
       [-0.14550003, -0.65364362,  0.75390225, -0.9899925 , -0.41614684]])

In [44]:
np.tan(array1)

array([[-0.29100619,  1.15782128,  1.55740772, -0.29100619, -6.79971146],
       [-3.38051501,  1.15782128, -0.14254654, -2.18503986,  1.15782128],
       [-0.29100619, -6.79971146, -0.14254654, -2.18503986,  1.15782128],
       [-6.79971146,  1.15782128,  0.87144798, -0.14254654, -2.18503986]])

In [45]:
np.sum(array1)

90

In [46]:
np.mean(array1)

4.5

In [47]:
np.median(array1)

4.0

In [50]:
np.subtract(array1,array2)

array([[ 5, -2, -3,  3,  6],
       [ 1,  1, -1, -6, -3],
       [ 2,  5, -5,  1, -2],
       [ 7,  0,  1, -1,  0]])

In [52]:
np.min(array1)

1

In [53]:
np.max(array1)

8

In [54]:
np.var(array1)

4.45