In [3]:
# numpy is a numerical python which is used to perform operation in array or matrix where matrix is the sub part of array
# import numpy and give short cut np 
import numpy as np

In [4]:
#create a list
list=[1,2,3,4,5,6,7]
print(list)

[1, 2, 3, 4, 5, 6, 7]


In [5]:
# conver list into a array 
array_of_list=np.array(list)
array_of_list

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
type(array_of_list)# where nd denote to n diementional array

numpy.ndarray

In [7]:
#another way to conver list into array
np.asarray(list)

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#simalirly conver tuple into array
tuple=(1,2,3,4,5,6,7)
array_of_tuple=np.array(tuple)
array_of_tuple

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#another way to  conver tuple into array
tuple=(1,2,3,4,5,6,7)
array_of_tuple=np.asarray(tuple)
array_of_tuple

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# ndim :- function is used to find diemention of arry
array_of_list.ndim

1

In [11]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,0]
list3=[34,6,8,90]

In [12]:
arr_3_dim=np.array([[1,2,3,4,5],[6,7,8,9,0],[34,6,8,90]])

/tmp/ipykernel_13069/3001317434.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_3_dim=np.array([[1,2,3,4,5],[6,7,8,9,0],[34,6,8,90]])


In [13]:
arr_3_dim

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 0]), list([34, 6, 8, 90])],
      dtype=object)

In [14]:
type(arr_3_dim)

numpy.ndarray

In [15]:
arr_3_dim.ndim

1

In [16]:
mat=np.matrix(list1)

In [17]:
mat

matrix([[1, 2, 3, 4, 5]])

In [18]:
arr1=np.asarray(list1)

In [19]:
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [20]:
arr1[0]=100

In [21]:
arr1

array([100,   2,   3,   4,   5])

In [22]:
b=arr1.copy()

In [23]:
b

array([100,   2,   3,   4,   5])

In [24]:
arr1[0]=346

In [25]:
arr1

array([346,   2,   3,   4,   5])

In [26]:
b

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
iter=(i*i for i in range(5))

In [29]:
np.fromiter(iter,int)

array([ 0,  1,  4,  9, 16])

In [34]:

np.fromstring("23 45 6 7 ", sep =" ")

array([23., 45.,  6.,  7.])

In [35]:
arr_3_dim.shape

(3,)

In [37]:
arr_3_dim.size

3

In [39]:
arr_3_dim.dtype

dtype('O')