In [1]:
import numpy as np

In [2]:
arr=np.array([1,3,2,9,7,8,9,3,65])

In [3]:
arr

array([ 1,  3,  2,  9,  7,  8,  9,  3, 65])

In [4]:
np.sort(arr)

array([ 1,  2,  3,  3,  7,  8,  9,  9, 65])

In [5]:
np.nonzero(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [8]:
np.where(arr>2)

(array([1, 3, 4, 5, 6, 7, 8]),)

In [10]:
np.extract(arr>2,arr)

array([ 3,  9,  7,  8,  9,  3, 65])

In [14]:
# bytes swaping
np.bytes_(arr)

b'\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00A'

In [15]:
np.copy(arr)

array([ 1,  3,  2,  9,  7,  8,  9,  3, 65])

In [19]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [21]:
nm.zeros((5,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
nm.ones((5,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])