In [1]:
import numpy as np

In [4]:
# it is a method to create a list by range function it take only integr arrgument in the range
list(range(0,5))

[0, 1, 2, 3, 4]

In [9]:
# in numpy having a range function similar to the range function it take integr as well as floating point number in argument
a=np.arange(0.1,56.0)

In [10]:
type(a)

numpy.ndarray

In [11]:
#convert into a list 
list(a)

[0.1,
 1.1,
 2.1,
 3.1,
 4.1,
 5.1,
 6.1,
 7.1,
 8.1,
 9.1,
 10.1,
 11.1,
 12.1,
 13.1,
 14.1,
 15.1,
 16.1,
 17.1,
 18.1,
 19.1,
 20.1,
 21.1,
 22.1,
 23.1,
 24.1,
 25.1,
 26.1,
 27.1,
 28.1,
 29.1,
 30.1,
 31.1,
 32.1,
 33.1,
 34.1,
 35.1,
 36.1,
 37.1,
 38.1,
 39.1,
 40.1,
 41.1,
 42.1,
 43.1,
 44.1,
 45.1,
 46.1,
 47.1,
 48.1,
 49.1,
 50.1,
 51.1,
 52.1,
 53.1,
 54.1,
 55.1]

In [12]:
arr2=np.arange(0.1,56.0,0.2)

In [13]:
arr2

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1, 10.3, 10.5, 10.7, 10.9,
       11.1, 11.3, 11.5, 11.7, 11.9, 12.1, 12.3, 12.5, 12.7, 12.9, 13.1,
       13.3, 13.5, 13.7, 13.9, 14.1, 14.3, 14.5, 14.7, 14.9, 15.1, 15.3,
       15.5, 15.7, 15.9, 16.1, 16.3, 16.5, 16.7, 16.9, 17.1, 17.3, 17.5,
       17.7, 17.9, 18.1, 18.3, 18.5, 18.7, 18.9, 19.1, 19.3, 19.5, 19.7,
       19.9, 20.1, 20.3, 20.5, 20.7, 20.9, 21.1, 21.3, 21.5, 21.7, 21.9,
       22.1, 22.3, 22.5, 22.7, 22.9, 23.1, 23.3, 23.5, 23.7, 23.9, 24.1,
       24.3, 24.5, 24.7, 24.9, 25.1, 25.3, 25.5, 25.7, 25.9, 26.1, 26.3,
       26.5, 26.7, 26.9, 27.1, 27.3, 27.5, 27.7, 27.9, 28.1, 28.3, 28.5,
       28.7, 28.9, 29.1, 29.3, 29.5, 29.7, 29.9, 30

In [15]:
type(arr2)

numpy.ndarray

In [16]:
len(arr2)

280

In [17]:
list(arr2)

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001,
 10.300000000000002,
 10.500000000000002,
 

In [22]:
# linespace function it take three argument and one for starting 
# one for ending and one for divide the range in how many part
#e.g:

np.linspace(1,5,3)
# it is devide equal part

array([1., 3., 5.])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [26]:
#logspace data is used to divde a range in logs
np.logspace(1,3,10,base=2)

array([2.        , 2.33305808, 2.72158   , 3.1748021 , 3.70349885,
       4.32023896, 5.0396842 , 5.87893797, 6.85795186, 8.        ])

In [27]:
#zeros function create zero array and matric
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((2,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
np.zeros((2,4,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0

In [31]:
arr=np.zeros((2,4))

In [32]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr-1

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [35]:
arr/2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
#ones function create a array of ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [37]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.ones((4,5,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [39]:
arr1=np.ones((4,5))

In [40]:
arr1*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [41]:
arr1+2

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [42]:
arr1-2

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [43]:
arr1/2

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [44]:
#empty function create a array of empty
np.empty(4)

array([0., 0., 0., 0.])

In [47]:
np.empty((8,7))

array([[ 0.1,  1.1,  2.1,  3.1,  4.1,  5.1,  6.1],
       [ 7.1,  8.1,  9.1, 10.1, 11.1, 12.1, 13.1],
       [14.1, 15.1, 16.1, 17.1, 18.1, 19.1, 20.1],
       [21.1, 22.1, 23.1, 24.1, 25.1, 26.1, 27.1],
       [28.1, 29.1, 30.1, 31.1, 32.1, 33.1, 34.1],
       [35.1, 36.1, 37.1, 38.1, 39.1, 40.1, 41.1],
       [42.1, 43.1, 44.1, 45.1, 46.1, 47.1, 48.1],
       [49.1, 50.1, 51.1, 52.1, 53.1, 54.1, 55.1]])

In [49]:
#eye fumction gives identity matric
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# now we are coming in the random function
#1.) random.rand :- it generated a random data with range
np.random.rand(5)

array([0.33730516, 0.05579999, 0.72896246, 0.52602496, 0.3672281 ])

In [51]:
np.random.rand(1,5)

array([[0.76588341, 0.87413977, 0.09180962, 0.77589504, 0.83593578]])

In [56]:
np.random.rand(1,5,24)

array([[[0.39733789, 0.38864435, 0.05279519, 0.29583724, 0.15444098,
         0.55621668, 0.46369216, 0.50258607, 0.27571758, 0.06453429,
         0.41275038, 0.63332095, 0.97187413, 0.89934414, 0.46100506,
         0.59189532, 0.61099224, 0.94607326, 0.47826298, 0.28217252,
         0.09946391, 0.7714664 , 0.05973384, 0.20257242],
        [0.53776153, 0.48584199, 0.14449535, 0.58871187, 0.71172425,
         0.7983705 , 0.04365815, 0.93871727, 0.89358776, 0.64735169,
         0.7885343 , 0.12234617, 0.61185092, 0.35335806, 0.28168862,
         0.70677669, 0.43937037, 0.86303763, 0.01201775, 0.12854216,
         0.40649012, 0.29966094, 0.37988233, 0.24504801],
        [0.35289761, 0.89346718, 0.22465252, 0.43838745, 0.58875378,
         0.88685554, 0.00237097, 0.63930836, 0.22585559, 0.91181401,
         0.37884731, 0.27561918, 0.44037379, 0.95865911, 0.63332045,
         0.56393228, 0.98544419, 0.47767909, 0.13678403, 0.5072594 ,
         0.38518583, 0.5224106 , 0.14830485, 0.35941445]

In [57]:
np.random.randn(1,5)

array([[-1.12806946,  0.62988092,  1.24770875,  1.07059891,  0.83994073]])

In [60]:
arr=np.random.randint(1,5,(3,4))

In [61]:
arr

array([[1, 1, 1, 4],
       [4, 4, 1, 3],
       [3, 3, 4, 2]])

In [62]:
arr.size

12

In [63]:
arr.ndim

2

In [64]:
arr.shape

(3, 4)

In [67]:
arr.reshape(6,2)

array([[1, 1],
       [1, 4],
       [4, 4],
       [1, 3],
       [3, 3],
       [4, 2]])

In [75]:
arr2=np.random.randint(2,4,(3,4))

In [76]:
arr2

array([[3, 2, 2, 3],
       [3, 2, 3, 3],
       [2, 3, 2, 3]])

In [77]:
arr2>2

array([[ True, False, False,  True],
       [ True, False,  True,  True],
       [False,  True, False,  True]])

In [78]:
arr2[arr2>2]

array([3, 3, 3, 3, 3, 3, 3])

In [80]:
arr1=np.random.randint(1,6,(3,4))
arr1=np.random.randint(6,10,(3,4))

In [82]:
# arthmatic operation inex by in the array
arr1+arr2

array([[ 9, 10, 10, 10],
       [11, 11,  9, 10],
       [10, 10, 11, 11]])

In [83]:
arr1-arr2

array([[3, 6, 6, 4],
       [5, 7, 3, 4],
       [6, 4, 7, 5]])

In [84]:
arr1*arr2

array([[18, 16, 16, 21],
       [24, 18, 18, 21],
       [16, 21, 18, 24]])

In [85]:
arr1/arr2

array([[2.        , 4.        , 4.        , 2.33333333],
       [2.66666667, 4.5       , 2.        , 2.33333333],
       [4.        , 2.33333333, 4.5       , 2.66666667]])

In [88]:
arr3=np.random.randint(1,6,(3,3))
arr4=np.random.randint(6,10,(3,3))

In [91]:
# if we want to perform matrix multiplicatin the we used @ opperator
#(m,n) (j,k) 
# here must be n=j anf the result matrix is (m,k)
arr3@arr4

array([[72, 63, 50],
       [81, 78, 57],
       [72, 69, 50]])

In [97]:
# array brodcasting
arr4=np.zeros((4,5))

In [98]:
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
arr4+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [101]:
a=np.array([1,2,3,4,5])

In [102]:
arr4+a

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])